pipeline {
    agent any
    stages {
        stage('stage1'){
            steps{
                echo 'webhook test'
            }
        }
        stage('Deliver') {
            steps {
                echo 'Webhook test Completed!'
            }
        }
    }
}
